---
# Este fichero tiene que estar situado en la carpeta "config" de la
# gestión correspondiente (no aquí, ni en ningún otro módulo)
#
#
# osp (Oficina sin papeles)
# Posibles valores:
# true Habilita la oficina sin papeles con todos los valores por defecto
# hash de valores: Se indicarán los valores de las diferentes opciones
:osp:
  # Indica si al añadir un pdf a otro se debe de borrar o no
  # el fichero después de añadido (por defecto vale false)
  :pdf_add_rm: true
  :upload:
    # Indica como versionar los ficheros subidos cuando hay coincidencia de nombre.
    # Posibles valores:
    # :new Se añadirá nº de versión al fichero subido (valor por defecto)
    # :old Se añadirá nº de versión al fichero ya existente
    # :none No se versiona. El fichero subido reemplazará al existente
    :version: :new
    # Indica que hacer al subir un pdf cuyo nombre ya existe
    # Posibles valores:
    # :pre El fichero se añadirá por delante al ya existente
    # :post El fichero se añadirá por detrás al ya existente
    # :version No se hará un tratamiento especial y se seguirán los dictados
    # del tag :version (es el valor por defecto) 
    :pdf: :version
#
#
#:excluir_usuarios: true
#:excluir_paises: true
#:excluir_divisas: true
#:excluir_empresas: true
#:excluir_ejercicios: true
#:excluir_contadores: true
#:excluir_perfiles: true
#:excluir_accesos: true
#:excluir_historicos: true
#:excluir_gi: true

# Habilta la opción de mensajería
:noticias: true

# Control de p2p
# Posibles valores: O bien un número indicando el máximo número de p2p
:p2p: 30
# O un hash con límites por tags:
:p2p:
  :xls: 20
  :loff: 10
  :tot: 50
# Los tags anteriores están reservados:
# xls:  Listados que sólo generan excel
# loff: Listados que usan libreoffice para conversión a PDF o XLS
# tot:  Número total de procesos 

# API
#
# Para obtener el token de autentificación hay que enviar un request POST al server
# con los parámetros "usuario" y "password" a la URL: /api/login
# El resto de métodos que se definan en la API deberán comenzar su ruta con /api/
# (p.ej.: /api/venta/get_cliente), tienen que ser POST y Como parámetro obligatorio
# hay que pasar "jwt=xxxxx" donde "xxxxx" es el token obtenido con /api/login 
#
# Puede ser true (en este caso se asume el periodo de validez del token en 1 día)
:api: true
# o un hash con una clave (jwt_exp) indicando el periodo de validez del token en segundos (en el ejemplo 1 hora)
:api:
  :jwt_exp: 3600