now = Time.now

#######################  USUARIOS

unless Nimbus::Config[:excluir_usuarios]
  if Usuario.count == 0
    puts 'Usuarios'

    HUsuario.delete_all
    ActiveRecord::Base.connection.reset_pk_sequence!('usuarios')
    ActiveRecord::Base.connection.reset_pk_sequence!('h_usuarios')

    Usuario.create({
      codigo: 'admin',
      nombre: 'Administrador',
      admin: true,
      password_salt: '$2a$10$nE9JPk2VedGY40K2MWlJ2u',
      password_hash: '$2a$10$nE9JPk2VedGY40K2MWlJ2u7tPTIk1olvKDsh.b4L4spcLZXVj9vIe',
      password_fec_mod: now,
      pref: {}
    })
  end
end

#######################  PAISES

unless Nimbus::Config[:excluir_paises]
  puts 'Países'

  paises = [
    ['Afganistán','AF','AFG','004'],
    ['Åland, Islas','AX','ALA','248'],
    ['Albania','AL','ALB','008'],
    ['Alemania','DE','DEU','276'],
    ['Andorra','AD','AND','020'],
    ['Angola','AO','AGO','024'],
    ['Anguila','AI','AIA','660'],
    ['Antártida','AQ','ATA','010'],
    ['Antigua y Barbuda','AG','ATG','028'],
    ['Arabia Saudita','SA','SAU','682'],
    ['Argelia','DZ','DZA','012'],
    ['Argentina','AR','ARG','032'],
    ['Armenia','AM','ARM','051'],
    ['Aruba','AW','ABW','533'],
    ['Australia','AU','AUS','036'],
    ['Austria','AT','AUT','040'],
    ['Azerbaiyán','AZ','AZE','031'],
    ['Bahamas','BS','BHS','044'],
    ['Bangladesh','BD','BGD','050'],
    ['Barbados','BB','BRB','052'],
    ['Bahrein','BH','BHR','048'],
    ['Bélgica','BE','BEL','056'],
    ['Belice','BZ','BLZ','084'],
    ['Benin','BJ','BEN','204'],
    ['Bermudas','BM','BMU','060'],
    ['Belarús','BY','BLR','112'],
    ['Bolivia (Estado Plurinacional de)','BO','BOL','068'],
    ['Bonaire, San Eustaquio y Saba','BQ','BES','535'],
    ['Bosnia y Herzegovina','BA','BIH','070'],
    ['Botswana','BW','BWA','072'],
    ['Brasil','BR','BRA','076'],
    ['Brunei Darussalam','BN','BRN','096'],
    ['Bulgaria','BG','BGR','100'],
    ['Burkina Faso','BF','BFA','854'],
    ['Burundi','BI','BDI','108'],
    ['Bhután','BT','BTN','064'],
    ['Cabo Verde','CV','CPV','132'],
    ['Camboya','KH','KHM','116'],
    ['Camerún','CM','CMR','120'],
    ['Canadá','CA','CAN','124'],
    ['Qatar','QA','QAT','634'],
    ['Chad','TD','TCD','148'],
    ['Chile','CL','CHL','152'],
    ['China','CN','CHN','156'],
    ['Chipre','CY','CYP','196'],
    ['Colombia','CO','COL','170'],
    ['Comoras (las)','KM','COM','174'],
    ['Corea (República Popular Democrática de)','KP','PRK','408'],
    ['Corea (República de)','KR','KOR','410'],
    ['Costa de Marfil','CI','CIV','384'],
    ['Costa Rica','CR','CRI','188'],
    ['Croacia','HR','HRV','191'],
    ['Cuba','CU','CUB','192'],
    ['Curaçao','CW','CUW','531'],
    ['Dinamarca','DK','DNK','208'],
    ['Dominica','DM','DMA','212'],
    ['Ecuador','EC','ECU','218'],
    ['Egipto','EG','EGY','818'],
    ['El Salvador','SV','SLV','222'],
    ['Emiratos Árabes Unidos','AE','ARE','784'],
    ['Eritrea','ER','ERI','232'],
    ['Eslovaquia','SK','SVK','703'],
    ['Eslovenia','SI','SVN','705'],
    ['España','ES','ESP','724'],
    ['Estados Unidos de América','US','USA','840'],
    ['Estonia','EE','EST','233'],
    ['Etiopía','ET','ETH','231'],
    ['Filipinas','PH','PHL','608'],
    ['Finlandia','FI','FIN','246'],
    ['Fiji','FJ','FJI','242'],
    ['Francia','FR','FRA','250'],
    ['Gabón','GA','GAB','266'],
    ['Gambia','GM','GMB','270'],
    ['Georgia','GE','GEO','268'],
    ['Ghana','GH','GHA','288'],
    ['Gibraltar','GI','GIB','292'],
    ['Granada','GD','GRD','308'],
    ['Grecia','GR','GRC','300'],
    ['Groenlandia','GL','GRL','304'],
    ['Guadeloupe','GP','GLP','312'],
    ['Guam','GU','GUM','316'],
    ['Guatemala','GT','GTM','320'],
    ['Guayana Francesa','GF','GUF','254'],
    ['Guernsey','GG','GGY','831'],
    ['Guinea','GN','GIN','324'],
    ['Guinea Bissau','GW','GNB','624'],
    ['Guinea Ecuatorial','GQ','GNQ','226'],
    ['Guyana','GY','GUY','328'],
    ['Haití','HT','HTI','332'],
    ['Honduras','HN','HND','340'],
    ['Hong Kong','HK','HKG','344'],
    ['Hungría','HU','HUN','348'],
    ['India','IN','IND','356'],
    ['Indonesia','ID','IDN','360'],
    ['Iraq','IQ','IRQ','368'],
    ['Irán (República Islámica de)','IR','IRN','364'],
    ['Irlanda','IE','IRL','372'],
    ['Bouvet, Isla','BV','BVT','074'],
    ['Isla de Man','IM','IMN','833'],
    ['Navidad, Isla de','CX','CXR','162'],
    ['Islandia','IS','ISL','352'],
    ['Caimán, Islas','KY','CYM','136'],
    ['Cocos / Keeling, Islas','CC','CCK','166'],
    ['Cook, Islas','CK','COK','184'],
    ['Feroe, Islas','FO','FRO','234'],
    ['Georgia del Sur y las Islas Sandwich del Sur','GS','SGS','239'],
    ['Heard (Isla) e Islas McDonald','HM','HMD','334'],
    ['Malvinas [Falkland], Islas','FK','FLK','238'],
    ['Marianas del Norte, Islas','MP','MNP','580'],
    ['Marshall, Islas','MH','MHL','584'],
    ['Pitcairn','PN','PCN','612'],
    ['Salomón, Islas','SB','SLB','090'],
    ['Turcas y Caicos, Islas','TC','TCA','796'],
    ['Islas Ultramarinas Menores de los Estados Unidos','UM','UMI','581'],
    ['Vírgenes británicas, Islas','VG','VGB','092'],
    ['Vírgenes de los Estados Unidos, Islas','VI','VIR','850'],
    ['Israel','IL','ISR','376'],
    ['Italia','IT','ITA','380'],
    ['Jamaica','JM','JAM','388'],
    ['Japón','JP','JPN','392'],
    ['Jersey','JE','JEY','832'],
    ['Jordania','JO','JOR','400'],
    ['Kazajstán','KZ','KAZ','398'],
    ['Kenya','KE','KEN','404'],
    ['Kirguistán','KG','KGZ','417'],
    ['Kiribati','KI','KIR','296'],
    ['Kuwait','KW','KWT','414'],
    ['Laos, República Democrática Popular','LA','LAO','418'],
    ['Lesotho','LS','LSO','426'],
    ['Letonia','LV','LVA','428'],
    ['Líbano','LB','LBN','422'],
    ['Liberia','LR','LBR','430'],
    ['Libia','LY','LBY','434'],
    ['Liechtenstein','LI','LIE','438'],
    ['Lituania','LT','LTU','440'],
    ['Luxemburgo','LU','LUX','442'],
    ['Macao','MO','MAC','446'],
    ['Macedonia','MK','MKD','807'],
    ['Madagascar','MG','MDG','450'],
    ['Malasia','MY','MYS','458'],
    ['Malawi','MW','MWI','454'],
    ['Maldivas','MV','MDV','462'],
    ['Malí','ML','MLI','466'],
    ['Malta','MT','MLT','470'],
    ['Marruecos','MA','MAR','504'],
    ['Martinique','MQ','MTQ','474'],
    ['Mauricio','MU','MUS','480'],
    ['Mauritania','MR','MRT','478'],
    ['Mayotte','YT','MYT','175'],
    ['México','MX','MEX','484'],
    ['Micronesia (Estados Federados de)','FM','FSM','583'],
    ['Moldova (República de)','MD','MDA','498'],
    ['Mónaco','MC','MCO','492'],
    ['Mongolia','MN','MNG','496'],
    ['Montenegro','ME','MNE','499'],
    ['Montserrat','MS','MSR','500'],
    ['Mozambique','MZ','MOZ','508'],
    ['Myanmar','MM','MMR','104'],
    ['Namibia','NA','NAM','516'],
    ['Nauru','NR','NRU','520'],
    ['Nepal','NP','NPL','524'],
    ['Nicaragua','NI','NIC','558'],
    ['Níger','NE','NER','562'],
    ['Nigeria','NG','NGA','566'],
    ['Niue','NU','NIU','570'],
    ['Norfolk, Isla','NF','NFK','574'],
    ['Noruega','NO','NOR','578'],
    ['Nueva Caledonia','NC','NCL','540'],
    ['Nueva Zelandia','NZ','NZL','554'],
    ['Omán','OM','OMN','512'],
    ['Países Bajos','NL','NLD','528'],
    ['Pakistán','PK','PAK','586'],
    ['Palau','PW','PLW','585'],
    ['Palestina, Estado de','PS','PSE','275'],
    ['Panamá','PA','PAN','591'],
    ['Papua Nueva Guinea','PG','PNG','598'],
    ['Paraguay','PY','PRY','600'],
    ['Perú','PE','PER','604'],
    ['Polinesia Francesa','PF','PYF','258'],
    ['Polonia','PL','POL','616'],
    ['Portugal','PT','PRT','620'],
    ['Puerto Rico','PR','PRI','630'],
    ['Reino Unido de Gran Bretaña e Irlanda del Norte','GB','GBR','826'],
    ['Sahara Occidental','EH','ESH','732'],
    ['República Centroafricana (la)','CF','CAF','140'],
    ['Chequia','CZ','CZE','203'],
    ['Congo','CG','COG','178'],
    ['Congo (República Democrática del)','CD','COD','180'],
    ['Dominicana, República','DO','DOM','214'],
    ['Reunión','RE','REU','638'],
    ['Rwanda','RW','RWA','646'],
    ['Rumania','RO','ROU','642'],
    ['Rusia','RU','RUS','643'],
    ['Samoa','WS','WSM','882'],
    ['Samoa Americana','AS','ASM','016'],
    ['Saint Barthélemy','BL','BLM','652'],
    ['Saint Kitts y Nevis','KN','KNA','659'],
    ['San Marino','SM','SMR','674'],
    ['Saint Martin (parte francesa)','MF','MAF','663'],
    ['San Pedro y Miquelón','PM','SPM','666'],
    ['San Vicente y las Granadinas','VC','VCT','670'],
    ['Santa Helena, Ascensión y Tristán de Acuña','SH','SHN','654'],
    ['Santa Lucía','LC','LCA','662'],
    ['Santo Tomé y Príncipe','ST','STP','678'],
    ['Senegal','SN','SEN','686'],
    ['Serbia','RS','SRB','688'],
    ['Seychelles','SC','SYC','690'],
    ['Sierra leona','SL','SLE','694'],
    ['Singapur','SG','SGP','702'],
    ['Sint Maarten (parte neerlandesa)','SX','SXM','534'],
    ['República Árabe Siria','SY','SYR','760'],
    ['Somalia','SO','SOM','706'],
    ['Sri Lanka','LK','LKA','144'],
    ['Swazilandia','SZ','SWZ','748'],
    ['Sudáfrica','ZA','ZAF','710'],
    ['Sudán','SD','SDN','729'],
    ['Sudán del Sur','SS','SSD','728'],
    ['Suecia','SE','SWE','752'],
    ['Suiza','CH','CHE','756'],
    ['Suriname','SR','SUR','740'],
    ['Svalbard y Jan Mayen','SJ','SJM','744'],
    ['Tailandia','TH','THA','764'],
    ['Taiwán (Provincia de China)','TW','TWN','158'],
    ['Tanzania, República Unida de','TZ','TZA','834'],
    ['Tayikistán','TJ','TJK','762'],
    ['Territorio Británico del Océano Índico','IO','IOT','086'],
    ['Tierras Australes Francesas','TF','ATF','260'],
    ['Timor-Leste','TL','TLS','626'],
    ['Togo','TG','TGO','768'],
    ['Tokelau','TK','TKL','772'],
    ['Tonga','TO','TON','776'],
    ['Trinidad y Tabago','TT','TTO','780'],
    ['Túnez','TN','TUN','788'],
    ['Turkmenistán','TM','TKM','795'],
    ['Turquía','TR','TUR','792'],
    ['Tuvalu','TV','TUV','798'],
    ['Ucrania','UA','UKR','804'],
    ['Uganda','UG','UGA','800'],
    ['Uruguay','UY','URY','858'],
    ['Uzbekistán','UZ','UZB','860'],
    ['Vanuatu','VU','VUT','548'],
    ['Vaticano','VA','VAT','336'],
    ['Venezuela (República Bolivariana de)','VE','VEN','862'],
    ['Viet Nam','VN','VNM','704'],
    ['Wallis y Futuna','WF','WLF','876'],
    ['Yemen','YE','YEM','887'],
    ['Djibouti','DJ','DJI','262'],
    ['Zambia','ZM','ZMB','894'],
    ['Zimbabwe','ZW','ZWE','716']
  ]

  paises_cee = %w(DE HU AT IE BE IT BG LV CY LT HR LU DK MT SK NL SI PL ES PT EE GB FI CZ FR RO GR SE)

  paises.each {|p|
    cod = p[1]
    fp = Pais.find_by codigo: cod
    fp = Pais.new unless fp

    fp.codigo = cod
    fp.nombre = p[0] if fp.nombre.nil? || fp.nombre.empty?
    fp.codigo_iso3 = p[2]
    fp.codigo_num = p[3]
    if cod == 'ES'
      fp.tipo = 'N'
    elsif paises_cee.include?(cod)
      fp.tipo = 'C'
    else
      fp.tipo = 'R'
    end
    fp.user_id = 1

    fp.save
  }
end
