#!/usr/local/bin/ruby

nimbus = 'modulos/nimbus-core/script/nimbus'
p = (ENV['PWD'] || Dir.pwd).split('/')
p.pop while p.size > 1 && !File.exist?(p.join('/') + '/' + nimbus)

if p.size > 1
  Dir.chdir(p.join('/'))
  exec(nimbus, *ARGV) if File.exist?('Gemfile') && File.exist?('bin/rails')
end

puts 'No estás situado en ningún proyecto.'
