#!/usr/local/bin/ruby

nimbus = 'modulos/nimbus-core/script/nimbus'
Dir.chdir('..') while Dir.pwd != '/' && !File.exists?(nimbus)

if Dir.pwd == '/'
  puts 'No estás situado en ningún proyecto.'
  exit
end

exec nimbus, *ARGV
