source 'https://rubygems.org'

gem 'rails', '7.0.2.2'
gem 'pg'
gem "sprockets-rails"
gem "turbolinks"
gem 'bcrypt'
gem 'jquery-rails'
gem 'puma'

gem 'openssl'
gem 'rdoc'
gem 'caxlsx'
gem 'simple_xlsx_reader'
gem 'matrix'
gem 'prawn'
gem 'rest-client'
# Para el uso de la API (opcional)
gem 'jwt'

# Compresión de javascript
gem 'terser'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use SCSS for stylesheets
gem 'sassc-rails'
